/* eslint-disable import/prefer-default-export */
export const TEST = 'TEST';

// AUTH
export const CREATE_USER_PROFILE = 'CREATE_USER_PROFILE';
export const VERIFY_USER_PROFILE_EMAIL = 'VERIFY_USER_PROFILE_EMAIL';
export const VERIFY_USER_PROFILE_OTP = 'VERIFY_USER_PROFILE_OTP';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// LandingPage
export const GET_IN_TOUCH_REQUEST = 'GET_IN_TOUCH_REQUEST';
export const GET_IN_TOUCH_REQUEST_SUCCESS = 'GET_IN_TOUCH_REQUEST_SUCCESS';
export const GET_IN_TOUCH_REQUEST_FAIL = 'GET_IN_TOUCH_REQUEST_FAIL';
export const GET_ALLNFT_REQUEST = 'GET_ALLNFT_REQUEST';
export const GET_ALLNFT_REQUEST_SUCCESS = 'GET_ALLNFT_REQUEST_SUCCESS';
export const GET_ALLNFT_REQUEST_FAIL = 'GET_ALLNFT_REQUEST_FAIL';
export const SUBSCRIBE_NEWSLETTER = 'SUBSCRIBE_NEWSLETTER';

// NFT
export const SAVE_NFT_COLLECTION = 'SAVE_NFT_COLLECTION';
export const SAVE_NFT_COLLECTION_SUCCESS = 'SAVE_NFT_COLLECTION_SUCCESS';
export const EDIT_NFT_COLLECTION = 'EDIT_NFT_COLLECTION';
export const GET_NFT_DETAILS = 'GET_NFT_DETAILS';
export const GET_NFT_DETAILS_SUCCESS = 'GET_NFT_DETAILS_SUCCESS';
export const GET_NFT_DETAILS_FAIL = 'GET_NFT_DETAILS_FAIL';
export const CREATE_NFT_HISTORY = 'CREATE_NFT_HISTORY';
export const GET_NFT_HISTORY = 'GET_NFT_HISTORY';
export const GET_NFT_HISTORY_SUCCESS = 'GET_NFT_HISTORY_SUCCESS';
export const SELL_NFT_COLLECTION = 'SELL_NFT_COLLECTION';
export const OPEN_WALLET_POPUP = 'OPEN_WALLET_POPUP';
