/* eslint-disable import/prefer-default-export */
export const TEST = 'TEST';

// AUTH

export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_REQUEST_SUCCESS = 'OTP_VERIFY_REQUEST_SUCCESS';
export const OTP_VERIFY_REQUEST_FAIL = 'OTP_VERIFY_REQUEST_FAIL';
export const CREATE_USER_PROFILE = 'CREATE_USER_PROFILE';
export const VERIFY_USER_PROFILE_EMAIL = 'VERIFY_USER_PROFILE_EMAIL';
export const VERIFY_USER_PROFILE_OTP = 'VERIFY_USER_PROFILE_OTP';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_IS_ADMIN = 'CHANGE_IS_ADMIN';
export const CHANGE_IS_SUPER_ADMIN = 'CHANGE_IS_SUPER_ADMIN';

// Administrator

export const GET_ADMINISTRATOR_LIST = 'GET_ADMINISTRATOR_LIST';
export const GET_ADMINISTRATOR_LIST_SUCCESS = 'GET_ADMINISTRATOR_LIST_SUCCESS';
export const GET_ADMINISTRATOR_LIST_FAIL = 'GET_ADMINISTRATOR_LIST_FAIL';
export const GET_ADMIN_DETAILS = 'GET_ADMIN_DETAILS';
export const GET_ADMIN_DETAILS_SUCCESS = 'GET_ADMIN_DETAILS_SUCCESS';
export const GET_ADMIN_DETAILS_FAIL = 'GET_ADMIN_DETAILS_FAIL';
export const CREATE_ADMIN = 'CREATE_ADMIN';
export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';
export const CREATE_ADMIN_FAIL = 'CREATE_ADMIN_FAIL';
export const EDIT_ADMIN = 'EDIT_ADMIN';
export const EDIT_ADMIN_SUCCESS = 'EDIT_ADMIN_SUCCESS';
export const EDIT_ADMIN_FAIL = 'EDIT_ADMIN_FAIL';
export const GET_SINGLE_ADMIN = 'GET_SINGLE_ADMIN';
export const GET_SINGLE_ADMIN_SUCCESS = 'GET_SINGLE_ADMIN_SUCCESS';
export const GET_SINGLE_ADMIN_FAIL = 'GET_SINGLE_ADMIN_FAIL';
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_FAIL = 'DELETE_ADMIN_FAIL';

// Role Management

export const CREATE_ROLE = 'CREATE_ROLE';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAIL = 'CREATE_ROLE_FAIL';
export const EDIT_ROLE = 'EDIT_ROLE';
export const EDIT_ROLE_SUCCESS = 'EDIT_ROLE_SUCCESS';
export const EDIT_ROLE_FAIL = 'EDIT_ROLE_FAIL';
export const DELETE_ROLE = 'DELETE_ROLE';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAIL = 'DELETE_ROLE_FAIL';
export const GET_ROLE_LIST = 'GET_ROLE_LIST';
export const GET_ROLE_LIST_SUCCESS = 'GET_ROLE_LIST_SUCCESS';
export const GET_ROLE_LIST_FAIL = 'GET_ROLE_LIST_FAIL';
export const GET_SINGLE_ROLE = 'GET_SINGLE_ROLE';
export const GET_SINGLE_ROLE_SUCCESS = 'GET_SINGLE_ROLE_SUCCESS';
export const GET_SINGLE_ROLE_FAIL = 'GET_SINGLE_ROLE_FAIL';

// NFT
export const SAVE_NFT_COLLECTION = 'SAVE_NFT_COLLECTION';
export const SAVE_NFT_COLLECTION_SUCCESS = 'SAVE_NFT_COLLECTION_SUCCESS';
export const EDIT_NFT_COLLECTION = 'EDIT_NFT_COLLECTION';
export const GET_NFT_DETAILS = 'GET_NFT_DETAILS';
export const GET_NFT_DETAILS_SUCCESS = 'GET_NFT_DETAILS_SUCCESS';
export const CREATE_NFT_HISTORY = 'CREATE_NFT_HISTORY';
export const SELL_NFT_COLLECTION = 'SELL_NFT_COLLECTION';
export const GET_ALLNFT_REQUEST = 'GET_ALLNFT_REQUEST';
export const GET_ALLNFT_REQUEST_SUCCESS = 'GET_ALLNFT_REQUEST_SUCCESS';
export const GET_ALLNFT_REQUEST_FAIL = 'GET_ALLNFT_REQUEST_FAIL';
export const NFT_IMAGE_PREVIEW = 'NFT_IMAGE_PREVIEW';
export const NFT_IMAGE_PREVIEW_SUCCESS = 'NFT_IMAGE_PREVIEW_SUCCESS';
export const NFT_IMAGE_PREVIEW_FAIL = 'NFT_IMAGE_PREVIEW_FAIL';
export const GET_COLLECTION_LIST = 'GET_COLLECTION_LIST';
export const GET_COLLECTION_LIST_SUCCESS = 'GET_COLLECTION_LIST_SUCCESS';
export const GET_COLLECTIBLE_TICKET_LIST = 'GET_COLLECTIBLE_TICKET_LIST';
export const GET_COLLECTIBLE_TICKET_LIST_SUCCESS = 'GET_COLLECTIBLE_TICKET_LIST_SUCCESS';

// Analytics
export const GET_ANALYTICS_LIST = 'GET_ANALYTICS_LIST';
export const GET_ANALYTICS_LIST_SUCCESS = 'GET_ANALYTICS_LIST_SUCCESS';
export const GET_ANALYTICS_LIST_FAIL = 'GET_ANALYTICS_LIST_FAIL';
