/* eslint-disable import/prefer-default-export */

import { makeStyles } from '@material-ui/core/styles';

// eslint-disable-next-line no-unused-vars
export const useStyles = makeStyles((theme) => ({
  app: {
    padding: '120px 0px 40px',
    textAlign: 'center',
    height: 'auto',
    marginTop: '-70px',
    background: 'white',
    boxSizing: 'border-box',
    minHeight: '800px',
    borderRadius: '80px 80px 0px 0px',
    justifyContent: 'center',
    [theme.breakpoints.down('xs')]: {
      padding: '60px 0px',
      justifyContent: 'center',
      alignItems: 'center',
    },
  },
  header1: {
    fontWeight: 900,
    fontSize: '35px',
    fontFamily: 'TomicaBlack',
    lineHeight: '35px',
    textAlign: 'center',
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
    color: '#00FF47',
    textShadow: '2px 2px 0px #000000;',
    [theme.breakpoints.down('xs')]: {
      fontSize: '26px',
      padding: '0px 40px',
    },
  },
  header3: {
    fontSize: '15px',
    marginTop: '20px',
    fontWeight: 'light',
    lineHeight: '24px',
    fontFamily: 'Tomica',
    color: '#5E6282',
    textAlign: 'left',
    marginLeft: 'auto',
    marginRight: 'auto',
    width: '50%',
    [theme.breakpoints.down('xs')]: {
      fontSize: '12px',
      minWidth: '70%',
      maxWidth: '90%',
      width: 'auto',
      lineHeight: '20px',
    },
  },
  cardsContainer: {
    padding: '0px 100px',
    display: 'flex',
    marginLeft: '30px',
    flexDirection: 'row',
    justifyContent: 'center',
    [theme.breakpoints.down('xs')]: {
      padding: '40px 0px',
      display: 'flex',
      flexDirection: 'row',
      marginLeft: '0px',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
  },
  cardBox: {
    flexDirection: 'column',
    position: 'relative',
    justifyContent: 'center',
    cursor: 'pointer !important',
    display: 'flex',
    alignItems: 'center',
    marginRight: '50px',
    marginTop: '70px',
    [theme.breakpoints.down('xs')]: {
      flexDirection: 'column',
      position: 'relative',
      marginTop: '20px',
      marginRight: '0px',
    },
  },
  card2: {
    width: '270px',
    position: 'static',
    height: '390px',
    border: '1px solid #00FF47',
    borderRadius: '69px',
    padding: '130px 30px 50px',
    top: '270px',
    marginTop: '-50px',
    // zIndex: '-1',
    boxSizing: 'border-box',
    [theme.breakpoints.down('xs')]: {
      minHeight: '250px',
      maxHeight: '300px',
      position: 'static',
      padding: '70px 30px 50px',
      marginBottom: '70px',
      marginTop: '-50px',
    },
  },
  activeLink: {
    width: '200px',
    height: '30px',
    padding: '8px 5px',
    background: 'linear-gradient(90deg, #00FF47 1.89%, #1CD9A0 100%);',
    border: '1px solid #000000',
    borderRadius: '100px',
    fontWeight: 'bold',
    cursor: 'pointer !important',
    fontSize: '16px',
    paddingTop: '12px',
  },
  popupRoot: {
    // top: '0 !important',
    height: '100%',
    width: '100%',
    position: 'static',
    backgroundColor: '#808080a3',
    // left: '0 !important',
  },
  popupPaper: {
    top: '15% !important',
    left: '25% !important',
    minHeight: '520px',
    maxHeight: 'auto',
    width: '800px',
    background: 'white',
    padding: '0px 0px',
    justifyContent: 'center',
    border: '0.5px solid #FFFFFF',
    boxShadow: '10px 10px 21px rgba(0, 0, 0, 0.22)',
    borderRadius: '73px',
    '&::-webkit-scrollbar': {
      width: '0.4em',
      color: 'red',
    },
    [theme.breakpoints.down('lg')]: {
      top: '10% !important',
      left: '19% !important',
    },
    [theme.breakpoints.down('md')]: {
      top: '10% !important',
      left: '12% !important',
    },
    [theme.breakpoints.down('sm')]: {
      top: '10% !important',
      left: '2% !important',
    },
    [theme.breakpoints.down('xs')]: {
      height: '100%',
      top: '2% !important',
      left: '4% !important',
    },
  },
  topLink: {
    fontSize: '12px',
    lineHeight: '124.5%',
    letterSpacing: '0.065em',
    color: '#DF6951',
    fontFamily: 'TomicaLight',
    position: 'absolute',
    top: '-20px',
    [theme.breakpoints.down('xs')]: {
      fontSize: '11px',
      fontFamily: 'Tomica',
    },
  },
  bottomLink: {
    fontSize: '12px',
    lineHeight: '124.5%',
    letterSpacing: '0.065em',
    fontFamily: 'Tomica',
    color: '#DF6951',
    fontWeight: 'bold',
    position: 'absolute',
    top: '80px',
    [theme.breakpoints.down('xs')]: {
      fontSize: '11px',
      top: '70px',
    },
  },
  card2Header: {
    fontSize: '13px',
    fontFamily: 'Tomica',
    marginBottom: '10px',
    textAlign: 'left',
    fontWeight: '550',
    [theme.breakpoints.down('xs')]: {
      display: 'list-item',
      listStyleType: 'disc',
      listStylePosition: 'initial',
    },
  },
  cardButton: {
    position: 'absolute',
    bottom: '-16px',
    display: 'flex',
    cursor: 'pointer !important',
    alignItems: 'center',
    justifyContent: 'center',
    [theme.breakpoints.down('xs')]: {
      bottom: '35px',
    },
  },
  card1: {
    zIndex: '1',
    width: '290px',
    height: '377px',
    display: 'flex',
    border: '1px solid #000000',
    boxShadow: '(0px 100px 80px rgba(0, 0, 0, 0.02)) drop-shadow(0px 64.8148px 46.8519px rgba(0, 0, 0, 0.0151852)) drop-shadow(0px 38.5185px 25.4815px rgba(0, 0, 0, 0.0121481)) drop-shadow(0px 20px 13px rgba(0, 0, 0, 0.01)) drop-shadow(0px 8.14815px 6.51852px rgba(0, 0, 0, 0.00785185)) drop-shadow(0px 1.85185px 3.14815px rgba(0, 0, 0, 0.00481481))',
    borderRadius: '30px 0px',
    flexDirection: 'column',
    // borderRadius: '24px',
    // backgroundColor: 'white',
    [theme.breakpoints.down('xs')]: {
      width: '270px',
      height: '310px',
    },
  },
  inner1: {
    height: '75%',
  },
  inner2: {
    position: 'relative',
    height: '107px',
    background: 'rgba(255, 255, 255, 0.96)',
    marginTop: '-10px',
    width: '100%',
    borderRadius: '0px 0px 30px 0px',
    borderTop: '1px solid #000000',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    [theme.breakpoints.down('xs')]: {
      width: '270px',
      height: '310px',
      borderBottomLeftRadius: '24px',
    },
  },
  header4: {
    letterSpacing: '0.065em',
    fontSize: '14px',
    fontFamily: 'Tomica',
    color: '#5E6282',
    fontWeight: 'bold',
    [theme.breakpoints.down('xs')]: {
      fontSize: '12px',
    },
  },
  ethBox: {
    display: 'flex',
    flexDirection: 'row',
  },
  header6: {
    fontWeight: '700',
    fontSize: '14px',
    width: 'fit-content',
    color: '#5E6282',
    display: 'flex',
    fontFamily: 'Tomica',
    marginLeft: '5px',
    marginTop: '1px',
  },
  header7: {
    fontWeight: '550',
    fontSize: '11px',
    width: 'fit-content',
    color: '#5E6282',
    fontFamily: 'Tomica',
    marginTop: '2px',
  },
  header5: {
    fontWeight: 'bold',
    fontSize: '13px',
    fontFamily: 'Helvetica',
    letterSpacing: '0.065em',
    color: '#DF6951',
    [theme.breakpoints.down('xs')]: {
      fontSize: '12px',
    },
  },
  logoImage: {
    maxWidth: '289px',
    width: 'auto',
    maxHeight: '377px',
    height: 'auto',
    borderRadius: '30px 0px',
  },
  logoImage1: {
    marginLeft: '0px',
    marginTop: '0px',
    width: '100%',
    height: '310px',
    borderRadius: '30px 0px',
  },
  sectionDesktop: {
    display: 'none',
    [theme.breakpoints.up('sm')]: {
      display: 'flex',
    },
  },
  sectionMobile: {
    display: 'flex',
    [theme.breakpoints.up('sm')]: {
      display: 'none',
    },
  },
  '@media screen and (max-width: 350px)': {
    header4: {
      letterSpacing: '0.065em',
      fontSize: '10px',
      color: '#5E6282',
      fontWeight: 'bold',
    },
    header5: {
      fontSize: '10px',
    },
  },
  '@media screen and (min-width: 1200px)': {
    popupPaper: {
      left: '22% !important',
    },
  },
}));
