/* eslint-disable import/prefer-default-export */

import { makeStyles } from '@material-ui/core/styles';

// eslint-disable-next-line no-unused-vars
export const useStyles = makeStyles((theme) => ({
  app: {
    padding: '150px 150px 40px',
    textAlign: 'center',
    // background: '#E5E5E5',
    height: 'auto',
    boxSizing: 'border-box',
    justifyContent: 'center',
    [theme.breakpoints.down('sm')]: {
      padding: '50px 30px',
      marginTop: '-40px',
      justifyContent: 'center',
      alignItems: 'center',
    },
  },
  header1: {
    fontWeight: 600,
    fontSize: '18px',
    fontFamily: 'Tomica',
    lineHeight: '27px',
    color: '#5E6282',
    textAlign: 'left',
    [theme.breakpoints.down('sm')]: {
      fontSize: '18px',
    },
  },
  header2: {
    fontWeight: '100',
    fontSize: '58px',
    fontFamily: 'TomicaBlack',
    width: '90%',
    lineHeight: '58.52px',
    marginTop: '20px',
    textAlign: 'left',
    letterSpacing: '0.03em',
    color: '#14183E',
    [theme.breakpoints.down('sm')]: {
      fontSize: '41px',
      lineHeight: '41.57px',
    },
  },
  header3: {
    fontWeight: 'bold',
    fontFamily: 'TomicaBlack',
    fontSize: '19px',
    textAlign: 'left',
    letterSpacing: '0.035em',
    color: '#5E6282',
  },
  header4: {
    fontWeight: 'normal',
    fontSize: '16px',
    fontFamily: 'Tomica',
    textAlign: 'left',
    width: '70%',
    marginTop: '0px',
    color: '#5E6282',
    [theme.breakpoints.down('sm')]: {
      width: '100%',
    },
  },
  headerSeg1: {
    marginTop: '20px',
  },
  headerSeg2: {
    marginTop: '20px',
    display: 'flex',
  },
  headerSeg3: {
    marginTop: '30px',
    display: 'flex',
    position: 'relative',
  },
  iconImage5: {
    position: 'absolute',
    right: '20px',
    bottom: '0px',
  },
  header5: {
    fontWeight: 'bold',
    fontFamily: 'Tomica',
    fontSize: '19px',
    textAlign: 'left',
    color: 'black',
  },
  header6: {
    fontWeight: 'bold',
    fontFamily: 'Tomica',
    fontSize: '16px',
    textAlign: 'left',
    letterSpacing: '-0.005em',
    color: '#84829A',
  },
  header7: {
    fontWeight: '550',
    fontFamily: 'Tomica',
    fontSize: '14px',
    textAlign: 'left',
    letterSpacing: '-0.035em',
    color: '#84829A',
    [theme.breakpoints.down('sm')]: {
      fontSize: '12px',
    },
  },
  pLeft: {
    paddingLeft: '50px',
    [theme.breakpoints.down('sm')]: {
      paddingLeft: '30px',
    },
  },
  header8: {
    fontWeight: '550',
    fontSize: '19px',
    fontFamily: 'Tomica',
    textAlign: 'left',
    letterSpacing: '-0.015em',
    color: 'black',
    [theme.breakpoints.down('sm')]: {
      fontSize: '14px',
    },
  },
  header9: {
    fontWeight: '550',
    fontSize: '15px',
    fontFamily: 'Tomica',
    textAlign: 'left',
    letterSpacing: '-0.055em',
    marginTop: '10px',
    color: '#8A79DF',
    [theme.breakpoints.down('sm')]: {
      fontSize: '12px',
      marginTop: '0px',
    },
  },
  landingProgressBar: {
    width: '170px',
    height: '5px',
    borderRadius: '30px',
    marginTop: '8px',
    background: '#F5F5F5',
    [theme.breakpoints.down('sm')]: {
      width: '100%',
    },
  },
  progressBar: {
    background: '#8A79DF',
    width: '70px',
    height: '5px',
  },
  featureContainer: {
    paddingTop: '50px',
    width: '110%',
    [theme.breakpoints.down('md')]: {
      width: '100%',
    },
  },
  seg2: {
    paddingLeft: '20px',
    [theme.breakpoints.down('md')]: {
      paddingLeft: '50px',
    },
  },
  iconBox1: {
    backgroundColor: '#F0BB1F',
    width: '50px',
    height: '50px',
    marginTop: '5px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '13px',
  },
  iconBox2: {
    backgroundColor: '#F15A2B',
    marginTop: '5px',
    width: '50px',
    height: '50px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '13px',
  },
  iconBox3: {
    backgroundColor: '#006380',
    marginTop: '5px',
    width: '50px',
    height: '50px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '13px',
  },
  iconBox6: {
    width: '54px',
    height: '54px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '50%',
    [theme.breakpoints.down('sm')]: {
      width: '30px',
      height: '30px',
    },
  },
  iconBox4: {
    backgroundColor: '#F5F5F5;',
    width: '40px',
    height: '40px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '50%',
    marginRight: '20px',
  },
  imageBox: {
    position: 'relative',
    paddingLeft: '50px',
    [theme.breakpoints.down('sm')]: {
      marginTop: '80px',
      paddingLeft: '0px',
    },
  },
  ongoingContainer: {
    zIndex: '2',
    top: '225px',
    right: '-100px',
    width: '300px',
    height: '140px',
    background: 'white',
    position: 'absolute',
    boxShadow: '0px 100px 80px rgba(0, 0, 0, 0.02), 0px 64.8148px 46.8519px rgba(0, 0, 0, 0.0151852), 0px 38.5185px 25.4815px rgba(0, 0, 0, 0.0121481), 0px 20px 13px rgba(0, 0, 0, 0.01), 0px 8.14815px 6.51852px rgba(0, 0, 0, 0.00785185), 0px 1.85185px 3.14815px rgba(0, 0, 0, 0.00481481)',
    borderRadius: '18px',
    padding: '30px',
    boxSizing: 'border-box',
    [theme.breakpoints.down('md')]: {
      right: '-70px',
    },
    [theme.breakpoints.down('sm')]: {
      width: '200px',
      height: '100px',
      right: '-60px',
      top: '170px',
      padding: '10px',
    },
  },
  backgroundBox: {
    zIndex: '-1',
    top: '-32px',
    left: '270px',
    width: '179px',
    filter: 'blur(78px)',
    height: '200px',
    background: '#59B1E6',
    opacity: 0.8,
    position: 'absolute',
    [theme.breakpoints.down('sm')]: {
      left: '50%',
    },
  },
  imageCard: {
    width: '350px',
    zIndex: '1',
    top: '-167px',
    left: '-139px',
    height: '380px',
    background: '#FFFFFF',
    boxShadow: '0px 100px 80px rgba(0, 0, 0, 0.02), 0px 64.8148px 46.8519px rgba(0, 0, 0, 0.0151852), 0px 38.5185px 25.4815px rgba(0, 0, 0, 0.0121481), 0px 20px 13px rgba(0, 0, 0, 0.01), 0px 8.14815px 6.51852px rgba(0, 0, 0, 0.00785185), 0px 1.85185px 3.14815px rgba(0, 0, 0, 0.00481481)',
    borderRadius: '26px',
    padding: '25px',
    [theme.breakpoints.down('sm')]: {
      width: '240px',
      height: '300px',
      marginLeft: '-50px',
    },
  },
  dFlex: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionDesktop: {
    display: 'none',
    [theme.breakpoints.up('md')]: {
      display: 'flex',
    },
  },
  sectionMobile: {
    display: 'flex',
    [theme.breakpoints.up('md')]: {
      display: 'none',
    },
  },
  '@media screen and (max-width: 320px)': {
    imageCard: {
      marginLeft: '10px',
      width: '228px',
    },
    ongoingContainer: {
      right: '-9px',
      width: '193px',
    },
    backgroundBox: {
      left: '42%',
    },
  },
}));
