/* eslint-disable import/prefer-default-export */

import { makeStyles } from '@material-ui/core/styles';

export const buttonStyles = makeStyles((theme) => ({
  button: {
    width: '180px !important',
    height: '40px !important',
    marginRight: '20px !important',
    backgroundColor: '#5200FF !important',
    fontStyle: 'normal',
    marginLeft: '15px !important',
    fontWeight: 450,
    fontSize: '12px !important',
    [theme.breakpoints.down('md')]: {
      width: '120px',
      padding: '10px 10px',
      fontSize: '10px',
    },
  },
}));

// eslint-disable-next-line no-unused-vars
export const useStyles = makeStyles((theme) => ({
  app: {
    padding: '50px 0px 40px',
    textAlign: 'center',
    height: 'auto',
    boxSizing: 'border-box',
    minHeight: '80vh',
    justifyContent: 'center',
    [theme.breakpoints.down('xs')]: {
      padding: '60px 0px',
      justifyContent: 'center',
      alignItems: 'center',
    },
  },
  header1: {
    fontWeight: 900,
    fontSize: '33px',
    fontFamily: 'Tomica',
    lineHeight: '33px',
    textAlign: 'center',
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
    color: '#00FF47',
    textShadow: '0 0 2px #000000, 0 0 2px #000000',
    [theme.breakpoints.down('xs')]: {
      fontSize: '26px',
      padding: '0px 40px',
    },
  },
  header1a: {
    fontWeight: 550,
    fontSize: '33px',
    // fontFamily: 'Tomica',
    lineHeight: '33px',
    textAlign: 'center',
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
    marginTop: '-5px',
    color: 'black',
    [theme.breakpoints.down('xs')]: {
      fontSize: '26px',
      padding: '0px 40px',
    },
  },
  header3: {
    fontWeight: 550,
    fontSize: '19px',
    fontFamily: 'Tomica',
    lineHeight: '50px',
    textAlign: 'center',
    letterSpacing: '0.08em',
    color: '#000000',
    // [theme.breakpoints.down('xs')]: {
    //   fontSize: '26px',
    //   padding: '0px 40px',
    // },
  },
  cardsContainer: {
    padding: '0px 80px',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    [theme.breakpoints.down('xs')]: {
      padding: '40px 0px',
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
  },
  cardBox: {
    flexDirection: 'column',
    position: 'relative',
    justifyContent: 'center',
    cursor: 'pointer !important',
    display: 'flex',
    alignItems: 'center',
    marginRight: '50px',
    marginTop: '60px',
    [theme.breakpoints.down('xs')]: {
      flexDirection: 'column',
      position: 'relative',
      marginTop: '0px',
      marginRight: '0px',
    },
  },
  cardBox1: {
    flexDirection: 'column',
    position: 'relative',
    justifyContent: 'center',
    cursor: 'not-allowed',
    display: 'flex',
    alignItems: 'center',
    marginRight: '50px',
    marginTop: '60px',
    [theme.breakpoints.down('xs')]: {
      flexDirection: 'column',
      position: 'relative',
      marginTop: '0px',
      marginRight: '0px',
    },
  },
  card1: {
    zIndex: '1',
    width: '265px',
    height: '320px',
    display: 'flex',
    flexDirection: 'column',
    // borderRadius: '24px',
    // backgroundColor: 'white',
    // [theme.breakpoints.down('xs')]: {
    //   width: '270px',
    //   height: '310px',
    // },
  },
  inner1: {
    height: '70%',
    display: 'flex',
    flexDirection: 'column',
    border: '1px solid #000000',
    borderRadius: '30px 0px 0px 0px',
  },
  inner1a: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    border: '1px solid #000000',
    borderRadius: '30px 0px 30px 0px',
  },
  portion1: {
    height: '40%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  portion1a: {
    height: '30%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  portion1Header: {
    fontWeight: 400,
    fontSize: '17px',
    fontFamily: 'Tomica',
    lineHeight: '33px',
    textAlign: 'center',
    letterSpacing: '0.065em',
    color: '#5E6282',
  },
  portion2: {
    height: '60%',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  inner2: {
    height: '30%',
    border: '1px solid #000000',
    backgroundColor: 'white',
    marginTop: '-10px',
    width: '100%',
    borderBottomRightRadius: '24px',
    display: 'flex',
    padding: '0px 30px',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    filter: 'drop-shadow(3px 4px 11px rgba(0, 0, 0, 0.14))',
    // [theme.breakpoints.down('xs')]: {
    //   width: '270px',
    //   height: '310px',
    //   borderBottomLeftRadius: '24px',
    // },
  },
  header2: {
    fontWeight: 400,
    fontSize: '13px',
    fontFamily: 'Tomica',
    lineHeight: '124.5%',
    textAlign: 'center',
    letterSpacing: '0.065em',
    color: '#5E6282',
  },
  header4: {
    letterSpacing: '0.065em',
    fontSize: '14px',
    fontFamily: 'Tomica',
    color: '#5E6282',
    fontWeight: 'bold',
    [theme.breakpoints.down('xs')]: {
      fontSize: '12px',
    },
  },
  sectionDesktop: {
    display: 'none',
    [theme.breakpoints.up('sm')]: {
      display: 'flex',
    },
  },
  sectionMobile: {
    display: 'flex',
    [theme.breakpoints.up('sm')]: {
      display: 'none',
    },
  },
  '@media screen and (max-width: 350px)': {
    header4: {
      letterSpacing: '0.065em',
      fontSize: '10px',
      color: '#5E6282',
      fontWeight: 'bold',
    },
    header5: {
      fontSize: '10px',
    },
  },
  '@media screen and (min-width: 1200px)': {
    popupPaper: {
      left: '22% !important',
    },
  },
}));
