/* eslint-disable import/prefer-default-export */

import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles({
  app: {
    background: '#fff',
    marginBottom: '0px',
  },
  uploadBox: {
    height: '400px',
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    border: '1px solid #000000',
    borderRadius: '30px 0px 24px',
    width: '100%',
    marginTop: '50px',
  },
  uploadBox1: {
    height: '400px',
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    border: '1px solid #000000',
    position: 'relative',
    borderRadius: '30px 0px 24px',
    background: 'linear-gradient(180deg, #F3F2EC 0%, rgba(255, 255, 255, 0) 100%)',
    padding: '50px',
    width: '100%',
    marginTop: '50px',
  },
  closeIcon: {
    position: 'absolute',
    right: '20px',
    cursor: 'pointer',
    top: '15px',
  },
  displayFlex: {
    display: 'flex',
    margin: '20px 0px',
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon1: {
    marginRight: '10px',
    marginTop: '6px',
  },
  leftGrid: {
    padding: '20px',
  },
  boxGrid: {
    // display: 'flex',
    justifyContent: 'center',
    padding: '0px 70px',
    boxSizing: 'border-box',
  },
  rightGrid: {
    display: 'flex',
    paddingRight: '5px',
    position: 'relative',
    flexDirection: 'column',
    padding: '20px 0px',
  },
  icon2Box: {
    position: 'absolute',
    display: 'flex',
    top: '28px',
    left: '-80px',
  },
  boxContent: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    // alignItems: 'center',
  },
  topSpace: {
    marginTop: '2vh',
  },
  subTitle: {
    fontSize: '12px',
    fontFamily: 'Tomica',
    fontWeight: '600',
  },
  title: {
    fontWeight: 450,
    fontFamily: 'TomicaBold',
    fontSize: '33px',
    textAlign: 'center',
    marginTop: '10px',
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
    color: 'black',
  },
  title1: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '18px',
    textAlign: 'center',
    marginTop: '10px',
    letterSpacing: '0.065em',
    color: '#5E6282',
    marginBottom: '40px',
  },
  title3: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '19px',
    marginTop: '-10px',
    marginLeft: '7px',
    opacity: '0.8',
    color: '#000000',
  },
  btnHeader: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '14px',
    letterSpacing: '0.025em',
    marginLeft: '5px',
    color: 'white',
  },
  submitBtn: {
    fontWeight: '450',
    height: '40px',
    fontFamily: 'Tomica',
    marginLeft: '15px',
    fontSize: '14px',
    color: 'white',
    backgroundColor: '#5200FF !important',
    fontStyle: 'normal',
  },
  imagePreview: {
    height: '100%',
    width: 'auto',
  },
  inputBtn: {
    display: 'none',
  },
  header1a: {
    fontWeight: 600,
    fontFamily: 'Tomica',
    textAlign: 'center',
    fontSize: '20px',
    marginTop: '0px',
    color: '#5E6282',
    letterSpacing: '0.065rem',
  },
  header1b: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    width: '100%',
    fontSize: '14px',
    textAlign: 'center',
    color: '#000000',
    lineHeight: '23px',
  },
  header1c: {
    fontWeight: 'bold',
    fontFamily: 'Tomica',
    width: '100%',
    fontSize: '14px',
    textAlign: 'center',
    color: '#000000',
    lineHeight: '23px',
  },
  header1cError: {
    fontWeight: 'bold',
    fontFamily: 'Tomica',
    width: '100%',
    fontSize: '14px',
    textAlign: 'center',
    color: 'red',
    lineHeight: '23px',
  },
  header1d: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    letterSpacing: '0.065rem',
    fontSize: '14px',
    textAlign: 'center',
    marginLeft: '20px',
    color: '#5E6282',
    marginTop: '50px',
    cursor: 'pointer',
    '&:hover': {
      cursor: 'pointer',
    },
  },
  header1e: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '16px',
    lineHeight: '30px',
    textAlign: 'left',
    marginLeft: '20px',
    color: '#000000',
    marginTop: '10px',
    position: 'absolute',
    top: '-30px',
    right: '10px',
    cursor: 'pointer',
    '&:hover': {
      cursor: 'pointer',
    },
  },
  header1f: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    letterSpacing: '0.065rem',
    fontSize: '14px',
    textAlign: 'center',
    marginLeft: '20px',
    color: '#5E6282',
    marginTop: '5px',
    cursor: 'pointer',
    '&:hover': {
      cursor: 'pointer',
    },
  },
  ethLogo: {
    position: 'absolute',
    top: '20px',
    right: '30px',
  },
  ethLogo1: {
    position: 'absolute',
    top: '3px',
    right: '30px',
  },
  dropdownStyle: {
    marginLeft: '0px',
    marginTop: '55px',
  },
  sendButton: {
    textAlignLast: 'end',
    textAlign: 'end',
    fontWeight: '450',
    height: '45px',
    fontFamily: 'Tomica',
    fontSize: '19px',
    color: 'white',
    backgroundColor: '#5200FF !important',
    fontStyle: 'normal',
    marginLeft: '30px !important',
    width: '100%',
    '&:disabled': {
      color: 'white',
      opacity: '0.8',
    },
    // '&:hover': {
    //   backgroundColor: '#00FF47',
    //   color: '#000000',
    // },
  },
  radioBtn: {
    marginLeft: '20px',
    marginTop: '-5px',
    marginRight: '-20px',
    marginBottom: '10px',
  },
  width100: {
    width: '100%',
    backgroundColor: '#E5E5E5',
    marginTop: '25px !important',
    height: '40px',
    padding: '0px !important',
  },
  colorWhite: {
    color: 'white !important',
  },
  successMessage: {
    color: '#00FF47',
    fontSize: '1rem',
    fontFamily: 'Tomica',
    textAlign: 'center',
    marginLeft: '2px',
    fontWeight: 'bold',
  },
  '@media screen and (min-width: 600px)': {
  },

  '@media screen and (max-width: 768px)': {
    title: {
      fontWeight: 900,
      fontSize: '33px',
      lineHeight: '33px',
      textAlign: 'center',
      letterSpacing: '0.13em',
      textTransform: 'uppercase',
      marginBottom: '20px',
    },
    subTitle: {
      fontSize: '12px',
      width: '80%',
      marginBottom: '5px',
    },
  },
});
