/* eslint-disable import/prefer-default-export */

import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles({
  app: {
    display: 'flex',
    marginTop: '50px',
    paddingLeft: '100px',
    paddingBottom: '100px',
    background: '#F8F8F8',
    boxShadow: '0px -13px 20px -16px rgba(0, 0, 0, 0.3)',
    borderRadius: '80px 80px 0px 0px',
    borderBottom: '1px solid #000000',
  },
  mainImageBox: {
    position: 'absolute',
    top: '-500px',
    cursor: 'pointer',
    width: '542px',
    height: '645px',
    borderRadius: '30px',
    filter: 'drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))',
    border: '1px solid  #000000',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    background: 'white',
  },
  zoomIcon: {
    position: 'absolute',
    top: '20px',
    right: '30px',
    // background: 'white',
  },
  mainImageBox1: {
    position: 'absolute',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    top: '-205px',
    left: '38%',
  },
  backImage: {
    maxWidth: '530px',
    maxHeight: '630px',
  },
  heading: {
    fontWeight: 900,
    fontFamily: 'TomicaBlack',
    fontSize: '33px',
    lineHeight: '33px',
    textAlign: 'left',
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
    color: '#00FF47',
    textShadow: '0 0 2px #000000, 0 0 2px #000000',
  },
  header1: {
    fontWeight: 600,
    fontFamily: 'Tomica',
    fontSize: '22px',
    color: 'black',
    marginLeft: '5px',
    textAlign: 'left',
    marginBottom: '20px',
    position: 'absolute',
  },
  header2: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '15px',
    lineHeight: '22px',
    textAlign: 'left',
    color: '#5E6282',
    marginTop: '30px',
  },
  header3: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '14px',
    lineHeight: '22px',
    marginLeft: '10px',
    color: '#5E6282',
    marginTop: '30px',
  },
  header3a: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '14px',
    lineHeight: '22px',
    marginLeft: '10px',
    color: '#5E6282',
  },
  header4: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    lineHeight: '16px',
    fontSize: '13px',
    marginLeft: '40px',
    color: '#5E6282',
  },
  header5: {
    fontWeight: 400,
    fontFamily: 'TomicaBold',
    lineHeight: '16px',
    fontSize: '13px',
    cursor: 'pointer',
    marginLeft: '5px',
    color: ' #1CD9A0',
  },
  header6: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '15px',
    margin: '0px 10px',
    color: 'black',
  },
  header7: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '12px',
    color: '#5E6282',
    textAlign: 'left',
    marginLeft: '10px',
  },
  header8: {
    fontWeight: 400,
    fontFamily: 'Tomica',
    fontSize: '13px',
    color: 'black',
    marginLeft: '15px',
  },
  topBox: {
    width: '420px',
    height: '45px',
    background: 'rgba(255, 255, 255, 0.85)',
    border: '1px solid #000000',
    boxShadow: '0px 100px 80px rgba(0, 0, 0, 0.02), 0px 64.8148px 46.8519px rgba(0, 0, 0, 0.0151852), 0px 38.5185px 25.4815px rgba(0, 0, 0, 0.0121481), 0px 20px 13px rgba(0, 0, 0, 0.01), 0px 8.14815px 6.51852px rgba(0, 0, 0, 0.00785185), 0px 1.85185px 3.14815px rgba(0, 0, 0, 0.00481481)',
    borderRadius: '30px 0px',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: '30px',
    marginTop: '80px',
  },
  interactBox: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: '180px',
  },
  interactBox1: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: '20px',
  },
  displayFlex: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '10px',
  },
  displayFlex1: {
    display: 'flex',
    // justifyContent: 'space-between',
    // alignItems: 'center',
    marginTop: '20px',
  },
  displayFlex2: {
    display: 'flex',
    flexDirection: 'column',
    // justifyContent: 'space-between',
    // alignItems: 'center',
    marginTop: '10px',
  },
  submitBtn1: {
    width: '141.46px',
    height: '38.72px',
    background: 'linear-gradient(90deg, #FFFFFF 1.89%, #1CD9A0 100%)',
    border: '1px solid #000000',
    borderRadius: '100px',
    fontWeight: 600,
    fontFamily: 'Tomica',
    lineHeight: '14px',
    fontSize: '14px',
    marginTop: '10px',
    color: 'black',
  },
  submitBtn2: {
    width: 'auto',
    height: '30px',
    background: 'white',
    border: '1px solid #000000',
    borderRadius: '100px',
    padding: '5px',
    marginLeft: '10px',
    fontWeight: 600,
    fontFamily: 'Tomica',
    lineHeight: '11px',
    fontSize: '12px',
    marginTop: '10px',
    color: '#8C8C8C',
  },
  submitBtn3: {
    width: '141.46px',
    height: '40px',
    border: '1px solid #000000',
    borderRadius: '100px',
    background: 'white',
    marginTop: '10px',
    padding: '0px !important',
    marginRight: '100px',
    color: 'black',
  },
});
